spring.application.name=taskmanager
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.access-expiration=900000
jwt.refresh-expiration=604800000
jwt.secret-key=dev-secret-key-for-local-testing-only-32chars!
